2024/02/14 17:14:00 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.29.0.3:9000", host: "localhost:8001"
2024/02/14 17:14:00 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.29.0.3:9000", host: "localhost:8001", referrer: "http://localhost:8001/"
